### ISSUE TITLE
Why are you using $timeout  0?

### ISSUE THREAD

**Issue by Lancezh** [thenikso/angular-flexslider#14]
Hi, bro

Could you tell me the reason Why are you using $timeout at the end of source code?

I am confused, thanks much 

<pre>
return $timeout((function() {
      return flexsliderDiv.flexslider(options);
}), 0);
</pre>

**Comment by PrimeByDesign** [comment]
Yup I found myself having to use $timeout(function { ... }, 0) in place of $(document).ready(function() {...})); This is because angular manipulates the DOM after the page has loaded. You can sometimes see angular expressions update after the pages have loaded when the CPU is a little busy. The timeout function ensures that the code is run zero milliseconds after angular has finished processing the document. I loath using it as it doesn't feel natural but once you get used to it... it's not so bad... It's certainly worth the tradeoff against the functionality angular provides.

**Comment by bob-lee** [comment]
I had a nasty situation that had to call angular.copy() right after angular.merge(). Seems that wrapping angular.copy inside $timeout with 0 timeout makes sure angular.merge() finished properly.
